### ISSUE TITLE
Image Security

### ISSUE THREAD

**Issue by wurstbrot** [wurstbrot/DevSecOps-MaturityModel#13]
Scanning images for OS vulnerabilities is less effective because you will wait for a patch, always.
Therefore it might be shifted to lvl 4.
As a replacement, the lifetime of images should be limited to enforce rebuild of images.

**Comment by louwersj** [comment]
"_**Scanning images for OS vulnerabilities is less effective because you will wait for a patch, always.
Therefore it might be shifted to lvl 4.**_". True... and,... it would be good practice to ensure / enforce scanning of an image during build time as well as in a pre-build time. 

in a pre-build time you could do (up to a certain level) static code analysis of your Dockerfile and other assets. 

During build-time you could check for issues / known CVEs that are still present after the build has been completed. 

"_**As a replacement, the lifetime of images should be limited to enforce rebuild of images.**_"
There is a lot to say for a (very) limited lifetime for images. It enforces nightly re-builds, it also helps against potential memory leaks and it helps to kill potentially compromised environments. 

Ideally this would be done in a two-step manner in my opinion. 

(1) each container has a set lifetime and is killed / replaced with a new container multiple times a day where you have some form of a graceful replacement to ensure no (short) service outage will occur to the end users. 
(2) twice a day a rebuild of images is done. The rebuilds are put into a automated testing pipeline. If the testing has no blocking issues the new images will be released for deployment during the next "restart" of a container. What has to be done, is to ensure the new containers are deployed in some canary deployment manner, this will ensure that if (and only if) something buggy has been introduced which breaks functionality the canary deployment will make sure the "older version" is being used and not the buggy newer one. 

In other words;

- Totally in favor of building new images multiple times a day or in a nightly build process. 
- Totally in favor of ensuring containers have a very limited lifetime. 
- Totally in favor of ensuring that functionality and availability is safeguarded by ensuring you have automated testing and canary style deployments in place. This however holds that you will first have to grow into those two areas prior to being able to introduce the automatic kill/re-deploy model 

just my 2 cents.

**Comment by wurstbrot** [comment]
@louwersj Do you think your comments are addressed appropriately?

**Comment by wurstbrot** [comment]
In case they are not addressed in your way, please open an other isse.
